[template]

src = "grafana.ini.tmpl"
dest = "grafana.ini"
verbose = true

keys = [
    "BUCKET_URL",
    "GRAFANA_URL",
    "MYSQL_URL",
    "MYSQL_PASS",
    "ADMIN_PASSWORD",
    "AWS_ACCESS_KEY",
    "AWS_SECRET_KEY"
]

owner = "root"
mode = "0755"
